Description: "A template for the CodeBuild getting started tutorial https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started-overview.html"

Resources:
  inputbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub codebuild-${AWS::Region}-${AWS::AccountId}-input-bucket
  outputbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub codebuild-${AWS::Region}-${AWS::AccountId}-output-bucket

  CodebuildServicePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CodeBuildServiceRolePolicy
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "CloudWatchLogsPolicy",
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Sid": "CodeCommitPolicy",
              "Effect": "Allow",
              "Action": [
                "codecommit:GitPull"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Sid": "S3GetObjectPolicy",
              "Effect": "Allow",
              "Action": [
                "s3:GetObject",
                "s3:GetObjectVersion"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Sid": "S3PutObjectPolicy",
              "Effect": "Allow",
              "Action": [
                "s3:PutObject"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Sid": "ECRPullPolicy",
              "Effect": "Allow",
              "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Sid": "ECRAuthPolicy",
              "Effect": "Allow",
              "Action": [
                "ecr:GetAuthorizationToken"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Sid": "S3BucketIdentity",
              "Effect": "Allow",
              "Action": [
                "s3:GetBucketAcl",
                "s3:GetBucketLocation"
              ],
              "Resource": 
                "*"
            }
          ]
        }

  CodebuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "codebuild.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      ManagedPolicyArns:
          - !Ref CodebuildServicePolicy
      RoleName: CodebuildServiceRole

  codebuildemoproject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: S3
        Location: !Ref outputbucket
        Name: /
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodebuildServiceRole
      Source:
        Location: !Sub ${inputbucket}/MessageUtil.zip
        Type: S3

  topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CodeBuildDemoTopic

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Statement:
          - Sid: AWSCodeStarNotifications_publish
            Effect: Allow
            Principal: 
              Service: codestar-notifications.amazonaws.com
            Action: SNS:Publish
            Resource: arn:aws:sns:us-east-1:406319049568:CodeBuildDemoTopic          
      Topics: 
        - !Ref topic


  subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: toby.ferguson@redislabs.com
      Protocol: email
      TopicArn: !Ref topic

  eventrule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.codebuild"
      State: ENABLED
      Targets:
        - Arn: !Ref topic
          Id: "CodeBuildDemoTopic_SNS"
      
Outputs:
  Project:
    Value: !Ref codebuildemoproject
    Description: Name of the CodeBuild Project
  InputBucket:
    Value: !Ref inputbucket
    Description: Name of the input bucket.
  OutputBucket:
    Description: S3 output bucket
    Value: !Ref outputbucket